language: node_js
node_js:
  - 12
install:
  - npm install
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: pre-deploy
      script: npm i -g vercel
    - stage: deploy-stage
      if: branch = staging
      env: PREVIEW_URL=https://v-test-2-staging.vercel.app
      script:
        - DEPLOY_URL=$(vercel --confirm -t $VERCEL_TOKEN)
        - vercel alias set $DEPLOY_URL $PREVIEW_URL -t $VERCEL_TOKEN
        
